"""
Milestone 5 — Grounded Response Generation
Retrieves top-k chunks, passes them to llama-3.3-70b-versatile via Groq,
enforces grounding via system prompt, appends source attribution programmatically.
"""

import os
import sys
from dotenv import load_dotenv
from groq import Groq
from retrieve import retrieve

load_dotenv()

LLM_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You are a helpful assistant for ASU students looking for off-campus housing in Tempe, Arizona.

Answer the question using ONLY the information in the provided documents below.
If the documents don't contain enough information to answer the question, say exactly:
"I don't have enough information on that."

Do not use any outside knowledge. Do not guess or infer beyond what the documents say.
Be specific and refer to apartment names when they appear in the documents."""


def build_context(chunks: list[dict]) -> str:
    parts = []
    for i, chunk in enumerate(chunks, 1):
        parts.append(f"[Document {i}]\n{chunk['text']}")
    return "\n\n".join(parts)


def build_sources(chunks: list[dict]) -> str:
    seen = set()
    sources = []
    for chunk in chunks:
        key = (chunk["apartment"], chunk["source"])
        if key not in seen:
            seen.add(key)
            line = f"• {chunk['apartment']} — {chunk['source']}"
            if chunk.get("url"):
                line += f" ({chunk['url']})"
            sources.append(line)
    return "\n".join(sources)


def generate(query: str, k: int = 5) -> dict:
    chunks = retrieve(query, k=k)

    if not chunks:
        return {
            "answer": "I don't have enough information on that.",
            "sources": "",
            "chunks": [],
        }

    context = build_context(chunks)
    user_message = f"Documents:\n{context}\n\nQuestion: {query}"

    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.2,  # low temperature for factual, grounded answers
        max_tokens=1024,
    )

    answer = response.choices[0].message.content.strip() # type: ignore
    # Source attribution is built programmatically from retrieved chunk metadata,
    # not generated by the LLM — guarantees attribution is always present and accurate
    sources = build_sources(chunks)

    return {"answer": answer, "sources": sources, "chunks": chunks}


if __name__ == "__main__":
    query = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Which apartments near ASU have a pool?"
    print(f"Query: {query}\n")

    result = generate(query)
    print("Answer:")
    print(result["answer"])
    print("\nSources:")
    print(result["sources"])
